// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/PortfolioContent/Detail/LiveBraille copy.md')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GTPlanner: typeof import('./components/PortfolioContent/Detail/GTPlanner.md')['default']
    HARRIS: typeof import('./components/PortfolioContent/Detail/HARRIS.md')['default']
    Header: typeof import('./components/Header.vue')['default']
    LC2D: typeof import('./components/PortfolioContent/Detail/LC2D.md')['default']
    LiveBraille: typeof import('./components/PortfolioContent/Detail/LiveBraille.md')['default']
    PCBEMG: typeof import('./components/PortfolioContent/Detail/PCBEMG.md')['default']
    README: typeof import('./components/README.md')['default']
    ResearchHub: typeof import('./components/PortfolioContent/Detail/ResearchHub.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RTSA: typeof import('./components/PortfolioContent/Detail/RTSA.md')['default']
    TapKeyboard: typeof import('./components/PortfolioContent/Detail/TapKeyboard.md')['default']
    TapProjects: typeof import('./components/PortfolioContent/Detail/TapProjects.md')['default']
    TipLetsWristLets: typeof import('./components/PortfolioContent/Detail/TipLetsWristLets.md')['default']
  }
}
