// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/PortfolioContent/Detail/LiveBraille copy.md')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GTPlanner: typeof import('./components/PortfolioContent/Detail/GTPlanner.md')['default']
    GTPlanner_: typeof import('./components/PortfolioContent/Preview/GTPlanner_.md')['default']
    HARRIS: typeof import('./components/PortfolioContent/Detail/HARRIS.md')['default']
    HARRIS_: typeof import('./components/PortfolioContent/Preview/HARRIS_.md')['default']
    Header: typeof import('./components/Header.vue')['default']
    LC2D: typeof import('./components/PortfolioContent/Detail/LC2D.md')['default']
    LC2D_: typeof import('./components/PortfolioContent/Preview/LC2D_.md')['default']
    LiveBraille: typeof import('./components/PortfolioContent/Detail/LiveBraille.md')['default']
    LiveBraille_: typeof import('./components/PortfolioContent/Preview/LiveBraille_.md')['default']
    PCBEMG: typeof import('./components/PortfolioContent/Detail/PCBEMG.md')['default']
    PCBEMG_: typeof import('./components/PortfolioContent/Preview/PCBEMG_.md')['default']
    README: typeof import('./components/README.md')['default']
    ResearchHub: typeof import('./components/PortfolioContent/Detail/ResearchHub.md')['default']
    ResearchHub_: typeof import('./components/PortfolioContent/Preview/ResearchHub_.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RTSA: typeof import('./components/PortfolioContent/Detail/RTSA.md')['default']
    RTSA_: typeof import('./components/PortfolioContent/Preview/RTSA_.md')['default']
    TapKeyboard: typeof import('./components/PortfolioContent/Detail/TapKeyboard.md')['default']
    TapKeyboard_: typeof import('./components/PortfolioContent/Preview/TapKeyboard_.md')['default']
    TapProjects: typeof import('./components/PortfolioContent/Detail/TapProjects.md')['default']
    TapProjects_: typeof import('./components/PortfolioContent/Preview/TapProjects_.md')['default']
    TipLetsWristLets: typeof import('./components/PortfolioContent/Detail/TipLetsWristLets.md')['default']
    TipLetsWristLets_: typeof import('./components/PortfolioContent/Preview/TipLetsWristLets_.md')['default']
  }
}
